version: '3'
services:

  # Application - Vökuró
  tutorial-8.0:
    build: resources/docker/8.0
    container_name: tutorial-8.0
    tty: true
    working_dir: /code
    depends_on:
      - tutorial-mysql
    volumes:
      - ./:/code
    networks:
      - tutorial-network

  tutorial-8.1:
    build: resources/docker/8.1
    container_name: tutorial-8.1
    tty: true
    working_dir: /code
    depends_on:
      - tutorial-mysql
    volumes:
      - ./:/code
    networks:
      - tutorial-network

  tutorial-8.2:
    build: resources/docker/8.2
    container_name: tutorial-8.2
    tty: true
    working_dir: /code
    depends_on:
      - tutorial-mysql
    volumes:
      - ./:/code
    networks:
      - tutorial-network

  tutorial-8.3:
    build: resources/docker/8.3
    container_name: tutorial-8.3
    tty: true
    working_dir: /code
    depends_on:
      - tutorial-mysql
    volumes:
      - ./:/code
    networks:
      - tutorial-network

  # Database - Mysql
  tutorial-mysql:
    image: mysql:5.7
    container_name: tutorial-mysql
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=phalcon
      - MYSQL_DATABASE=phalcon_tutorial
      - MYSQL_PASSWORD=secret
    volumes:
      - tutorial-volume:/var/lib/mysql/
    networks:
      - tutorial-network

# Network
networks:
  tutorial-network:
    driver: bridge

# Volumes
volumes:
  tutorial-volume:
    driver: local
